### PR TITLE
fix: licenseDeclared is not slice

### PR DESCRIPTION
**Pull request by thesayyn**
Signed-off-by: thesayyn <thesayyn@gmail.com>

### CODE REVIEW

**Comment by thesayyn** [comment]
ref: https://github.com/spdx/tools-golang/blob/97ef16cfc20c7ff192156fdebfc21401b360a965/spdx/v2_2/package.go#L76

**Review by djschleen — DISMISSED** [review]
Thank you!!!

**Comment by djschleen** [comment]
@thesayyn - can you use a signed commit?

**Comment by thesayyn** [comment]
done

**Pull request merged**
